[pyprland]

plugins = [
  "scratchpads",
  "magnify",
]

[scratchpads.term]
animation = "fromTop"
command = "kitty --class kitty-dropterm --title kitty"
class = "kitty-dropterm"
size = "75% 60%"
margin = 50
allow_special_workspaces = true
